field.field.*.*.*.third_party.composite_reference:
  type: mapping
  label: 'Composite reference settings'
  mapping:
    composite:
      type: boolean
      label: 'Whether the field is a composite reference or not.'
